# Travis CI Config
sudo: required
dist: xenial
language: generic

notifications:
  email:
    recipients:
      - mtreynolds@uwaterloo.ca
    on_success: change #[always|never|change] # default: change
    on_failure: change #[always|never|change] # default: always

env:
  global:

    # Run linters and style checks
    - CATKIN_CONFIG='-DCMAKE_EXPORT_COMPILE_COMMANDS=ON'
    - AFTER_SCRIPT="source /root/catkin_ws/install/setup.bash; cd /root/catkin_ws/src/frc_control; ./scripts/run_linters.py"
  matrix:
    - ROS_DISTRO="melodic"   ROS_REPO="ros"
    - ROS_DISTRO="melodic"   ROS_REPO="ros-testing"

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - .ci_config/travis.sh
