# Travis CI Config
sudo: required
dist: xenial
language: generic

notifications:
  email:
    recipients:
      - mtreynolds@uwaterloo.ca
    on_success: change #[always|never|change] # default: change
    on_failure: change #[always|never|change] # default: always

env:
  global:
  #   - CLANG_FORMAT_CHECK="file"
  #   - CLANG_FORMAT_VERSION="7"

        # TODO(matt.reynolds): Figure out how to run code analysis before catkin building.
        # The reason this isn't currently done is because clang-tidy relies on the build to
        # determine which files to lint and their relationship to each other.
      - CATKIN_CONFIG='-DCMAKE_EXPORT_COMPILE_COMMANDS=ON'
      - AFTER_SCRIPT="./check_code_style.sh"
  matrix:
    - ROS_DISTRO="melodic"   ROS_REPO="ros"
    - ROS_DISTRO="melodic"   ROS_REPO="ros-shadow-fixed"

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - .ci_config/travis.sh
